apiVersion: apps/v1
kind: Deployment
metadata:
  name: fail5
  labels:
    app: httpd
spec:
  replicas: 1
  selector:
    matchLabels:
      app: httpd
  template:
    metadata:
      labels:
        app: httpd
    spec:
      containers:
      - name: httpd
        image: registry.redhat.io/rhel8/python-38:latest
        resources:
          limits:
            cpu: "250m"
            memory: "100Mi"
        command:
        - bash
        args:
          - -c
          - python -c 'import sys;sys.exit(1)'
